name: sign_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^0.7.0
  animated_text_kit: ^1.3.1
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.15.2
  cloud_firestore: ^0.13.0+1
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.14.3
  cupertino_icons: ^0.1.2
  timeago: ^2.0.21
  google_sign_in: ^4.1.0
  transparent_image: ^1.0.0
  camera: ^0.5.6+3
  path_provider: ^1.5.1
  video_player: ^0.7.2
  http: ^0.12.0+2




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/ic_flutter_devs_logo.png
    - images/ic_powered_by.png
    - images/ic_switch_camera_3.png
    - images/ic_no_video.png
    - images/ic_play.png
    - images/ic_stop_video.png
    - images/ic_video_shutter.png
    - images/white.jpg
    - images/

